<?
$PERM["shopper"]["2"]="D";
$PERM["shopper"]["3"]="D";
$PERM["shopper"]["4"]="D";
$PERM["shopper"]["8"]="R";
$PERM["shopper"]["6"]="W";
$PERM["shopper"]["7"]="D";
$PERM["shopper"]["5"]="D";
$PERM["shopper"]["*"]="D";
$PERM["seller"]["2"]="D";
$PERM["seller"]["3"]="D";
$PERM["seller"]["4"]="D";
$PERM["seller"]["8"]="R";
$PERM["seller"]["6"]="D";
$PERM["seller"]["7"]="W";
$PERM["seller"]["5"]="D";
$PERM["seller"]["*"]="D";
$PERM["search"]["5"]="W";
$PERM["products"]["5"]="W";
$PERM["services"]["5"]="W";
$PERM["news"]["5"]="W";
$PERM["contacts"]["5"]="W";
$PERM["company"]["5"]="W";
$PERM["index.php"]["5"]="W";
$PERM["/"]["*"]="R";
?>